name: jobsy
description: A job matching app for clients and freelancers.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  shared_preferences: ^2.5.3
  http: ^1.3.0
  provider: ^6.1.4
  intl: ^0.19.0
  mask_text_input_formatter: ^2.4.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  collection: ^1.17.0
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon_2.png
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/logo.svg
    - assets/projects.svg
    - assets/archive.svg
    - assets/DrawKit Vector Illustration Team Work (3).svg
    - assets/onboarding1.svg
    - assets/onboarding2.svg
    - assets/onboarding3.svg
    - assets/onboarding4.svg
    - assets/icons/Home.svg
    - assets/icons/Search.svg
    - assets/icons/EyeInvisible.svg
    - assets/icons/EyeVisible.svg
    - assets/icons/Add.svg
    - assets/icons/Close.svg
    - assets/icons/Check.svg
    - assets/icons/ArrowLeft.svg
    - assets/icons/ArrowRight.svg
    - assets/icons/ArrowUp.svg
    - assets/icons/ArrowDown.svg
    - assets/icons/Profile.svg
    - assets/icons/Heart Filled.svg
    - assets/icons/Heart Outlined.svg
    - assets/icons/Trailing.svg
    - assets/icons/user.svg
    - assets/icons/Warning.svg
    - assets/icons/Inbox.svg
    - assets/icons/Info.svg
    - assets/icons/Success.svg
    - assets/icons/Delete.svg
    - assets/icons/solar_phone-bold.svg
    - assets/icons/calendar.svg
    - assets/icons/akar-icons_link-out.svg
    - assets/icons/checkTrue.svg
    - assets/icons/checkFalse.svg
    - assets/icons/avatar.svg
    - assets/unlog.svg
    - assets/icons/RadioButton.svg
    - assets/icons/RadioButton2.svg
    - assets/DrawKit9.svg
    - assets/delete_screen_confirmation.svg
    - assets/icons/user.svg
    - assets/icons/projects.svg
    - assets/icons/portfolio.svg
    - assets/icons/logout.svg
    - assets/icons/menu.svg
    - assets/icons/Filter.svg
    - assets/icons/company.svg
    - assets/icons/location.svg
    - assets/icons/star.svg
    - assets/icons/Edit.svg


