name: jobsy
description: A job matching app for clients and freelancers.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  shared_preferences: ^2.5.3
  http: ^1.3.0
  provider: ^6.1.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/projects.svg
    - assets/archive.svg
    - assets/onboarding1.svg
    - assets/onboarding2.svg
    - assets/onboarding3.svg
    - assets/onboarding4.svg
    - assets/projects.svg


    - assets/icons/home.svg
    - assets/icons/search.svg
    - assets/icons/profile.svg
